USE [C:\DESENVOLVIMENTO\REPOSITORIO\TESTE_EMPREGO\FI.WEBATIVIDADEENTREVISTA\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF];

ALTER TABLE CLIENTES ADD CPF VARCHAR(15);

update CLIENTES set CPF = '44784922040' where id = 16;	
update CLIENTES set CPF = '57125471048' where id = 17;

Alter table CLIENTES ALTER COLUMN CPF varchar(15) NOT NULL;

ALTER TABLE CLIENTES ADD CONSTRAINT UQ_CLIENTE_CPF UNIQUE(CPF);